Allow passing DB2_AUTOCOMMIT_* to db2_autocommit when using strict types
DB2_AUTOCOMMIT_ON and DB2_AUTOCOMMIT_OFF are defined as longs, but
db2_autocommit() takes a boolean. When strict types are enabled,
this results in an error even though the docs say you must pass
one of these values.

eg.

declare(strict_types=1);
db2_autocommit($c, DB2_AUTOCOMMIT_OFF);
TypeError: db2_autocommit() expects parameter 2 to be boolean, integer given

https://bugs.php.net/bug.php?id=77591

Signed-off-by: Kevin Adler <kadler@us.ibm.com>